# Generated by Django 2.1.7 on 2019-03-13 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shout_text', models.CharField(max_length=200)),
                ('shout_time', models.DateTimeField(default=datetime.datetime(2019, 3, 13, 18, 46, 26, 745962))),
            ],
        ),
    ]
